<a href="https://colab.research.google.com/github/USERASHOKG/AShok/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


Pytoch Documentation :



In [80]:
print("Hello Nieve freind Ashok here starting pytorch tutorial !!")

Hello Nieve freind Ashok here starting pytorch tutorial !!


In [81]:
import torch
torch.__version__

'2.5.1+cu124'

In [82]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


# **Introduction to Tensors**

**creating tensors**






In [83]:
#scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [84]:
scalar.ndim

0

In [85]:
scalar.item()

7

In [86]:
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [87]:
vector.ndim

1

In [88]:
vector.shape

torch.Size([2])

In [89]:
Matrix =torch.tensor([[2,3],[3,4],[4,6]])
Matrix

tensor([[2, 3],
        [3, 4],
        [4, 6]])

In [90]:
Matrix.ndim

2

In [91]:
Matrix.shape

torch.Size([3, 2])

In [92]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [93]:
TENSOR.shape

torch.Size([1, 3, 3])

In [94]:
TENSOR.ndim

3

In [95]:
#crete a  random tensor of size(3,4)

random_tensor = torch.ones(2,4)

In [96]:
random_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [97]:
random_tensor.dtype


torch.float32

In [98]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [99]:

left = torch.arange(0,10)

In [100]:
torch.__version__

'2.5.1+cu124'

In [101]:
ten = torch.zeros_like(input= left)
ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# ***Tensor datatype***

In [102]:
flo = torch.tensor([3.0, 6.0, 7.0],
                   dtype = None,
                   device = None,
                   requires_grad = False)
flo

tensor([3., 6., 7.])

In [103]:
flo.dtype

torch.float32

In [104]:
neu = torch.tensor([23,2,4],
                   dtype = torch.int64)
neu

tensor([23,  2,  4])

In [105]:
flo * neu

tensor([69., 12., 28.])

# *** One of three problem in deep learning in tensr***

In [106]:
#create a tensor
tensor = torch.rand([3,4]);
tensor

tensor([[0.7609, 0.2783, 0.8311, 0.6326],
        [0.1923, 0.3072, 0.3091, 0.3159],
        [0.4052, 0.9817, 0.4833, 0.7722]])

In [107]:
# check its attributes
print(tensor)
print(f"Datatypeof tensor: {tensor.dtype}")
print(f"shape of tensor: {tensor.shape}")
print(f"Device tensor is on :{tensor.device}")

tensor([[0.7609, 0.2783, 0.8311, 0.6326],
        [0.1923, 0.3072, 0.3091, 0.3159],
        [0.4052, 0.9817, 0.4833, 0.7722]])
Datatypeof tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device tensor is on :cpu


#manipulating the tensor (tesnor operations)

Tensor operations inlcude :
# Additon
# Substraction
## multiplication
# Division
# matrix multiplication

In [108]:
tensor = torch.tensor([1,2,3])

tensor +10

tensor([11, 12, 13])

In [109]:
tensor * 10

tensor([10, 20, 30])

In [110]:
tensor -19

tensor([-18, -17, -16])

In [111]:
torch.mul(tensor,2)

tensor([2, 4, 6])

In [112]:
tensor.add(10)

tensor([11, 12, 13])

In [113]:
tensor.sub(2)

tensor([-1,  0,  1])

# Matrix multioplication

1. Element wise multiplication
2.  Matrix multiplication (dot product)


In [114]:
#Element Multiplicatipon
print(tensor,"*",tensor);
print("ewuals to ",tensor* tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
ewuals to  tensor([1, 4, 9])


In [115]:
torch.matmul(tensor,tensor)

tensor(14)

In [116]:
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)


In [117]:
tensor @ tensor

tensor(14)

In [118]:
tenA = torch.tensor([[1,2],
                    [3,4],
                    [5,6]])

In [119]:
tenB = torch.tensor([[7,10],
                     [8,11]])

In [120]:
torch.matmul(tenA ,tenB)

tensor([[ 23,  32],
        [ 53,  74],
        [ 83, 116]])

In [121]:
tenA.shape, tenB.shape

(torch.Size([3, 2]), torch.Size([2, 2]))

In [122]:
tenA.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [123]:
# tesnor aggreagation

tensor = torch.arange(0,100,10)
tensor.dtype

torch.int64

In [124]:
torch.min(tensor)

tensor(0)

In [125]:
torch.max(tensor)

tensor(90)

In [126]:
torch.mean(tensor.type(torch.float32))

tensor(45.)

In [127]:
torch.sum(tensor)

tensor(450)

In [128]:
torch.argmin(tensor)

tensor(0)

In [129]:
torch.argmax(tensor)

tensor(9)

In [162]:
import torch
x = torch.arange(1,10);
x


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
 y = x.reshape(9,1)
print(y.shape)
y

torch.Size([9, 1])


tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [166]:
#Change the View
x = x.view(3,3)
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [167]:
# Stack tensors on top of each other
x= torch.stack([x, x, x, x], dim=2) # try changing dim to dim=1 and see what happens
x

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],

        [[4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6]],

        [[7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]])

In [55]:
tensor = torch.arange(1,10).reshape(1,3,3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [61]:
tensor.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
 m = tensor.unsqueeze(dim = 0)
 m

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

# **Permute**
torch.permute(change the index order)

In [6]:
import torch
x_original = torch.rand(size = (224,224,3))

x_new = x_original.permute(2,0,1)
x_original.shape
x_new.shape

torch.Size([3, 224, 224])

In [9]:
x_original[0,0,0] = 728218
x_original[0,0,0],x_new[0,0,0]

(tensor(728218.), tensor(728218.))

# indexing (selectin data form tensors)

indexinf witht the pytorch is similar to indexing with tht numpy


In [18]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [19]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
x[0,0]

tensor([1, 2, 3])

In [22]:
#Lets Index on the most inner bracket (last dimension)
x[0][0][1]

tensor(2)

In [36]:
x[ : , 2, 1]

tensor([8])

#NUmpy

# its Numerical Sientifc library

In [67]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.int32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [68]:
array.dtype

dtype('float64')

In [69]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [71]:
#change the value of the tensor
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [72]:
# tensor to Numpy array
tensor = torch.ones(7)
num = tensor.numpy()
tensor, num

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducability (trying to take the random out of random)

to reduce the randomenrsss in nural netwok and oytiorch comes te onper random used


In [73]:
torch.rand(3,3)

tensor([[0.7455, 0.2788, 0.4902],
        [0.0056, 0.5875, 0.8078],
        [0.4717, 0.6449, 0.6547]])

In [74]:
import torch

ranA =torch.rand(3,4)
ranB = torch.rand(3,4)

print(ranA)
print(ranB)
print(ranA == ranB)

tensor([[0.1291, 0.4745, 0.4344, 0.5224],
        [0.0881, 0.5157, 0.2702, 0.2037],
        [0.8333, 0.1186, 0.0610, 0.6401]])
tensor([[0.6901, 0.4843, 0.0385, 0.1769],
        [0.6113, 0.3489, 0.7422, 0.8144],
        [0.0722, 0.7351, 0.7166, 0.3967]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [82]:
# Let's make some random but reproducible tensors

import torch

ran = 42
torch.manual_seed(ran)
tx = torch.rand(3,4)
torch.manual_seed(ran)
tt = torch.rand(3,4)
print(tx)
print(tt)
print(tx == tt)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## runnning pytorcyh objects on the gpu making faster computuation
gpu = faster computaion, thanks to cuda + Nvidia hardware + pytorch working behind the scnence


In [1]:
!nvidia-smi

Sun Feb 16 13:12:17 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   33C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
#check the for gpu access with pytorch
import torch
torch.cuda.is_available()

True

In [3]:
# Setup device agnostic cuda
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

# **Putting tensors (and Models) on the gpu**


In [7]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
tensor_gpu = tensor.to(device)

tensor_gpu

tensor([1, 2, 3], device='cuda:0')

## **tensors run on gpu back to cpu**

In [11]:
tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [12]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [21]:
import torch

tensor = torch.tensor([1,2,3])

tensor, tensor.device


(tensor([1, 2, 3]), device(type='cpu'))

In [22]:
togpu = tensor.to(device)
togpu

tensor([1, 2, 3], device='cuda:0')

In [24]:
tocpu = togpu.cpu().numpy()
tocpu

array([1, 2, 3])

# Exercises


In [3]:
import torch
tensor = torch.rand(7,7)

tensor

tensor([[0.1883, 0.0732, 0.1876, 0.7504, 0.1002, 0.3947, 0.2346],
        [0.4978, 0.2126, 0.6293, 0.6710, 0.1732, 0.9077, 0.1092],
        [0.2753, 0.0723, 0.3915, 0.5710, 0.2054, 0.5094, 0.9715],
        [0.0026, 0.0507, 0.2360, 0.7965, 0.0871, 0.9030, 0.6168],
        [0.8568, 0.9317, 0.2068, 0.5016, 0.3314, 0.7381, 0.6940],
        [0.2231, 0.5356, 0.5959, 0.1444, 0.2291, 0.3582, 0.1365],
        [0.0194, 0.3941, 0.6570, 0.0961, 0.9198, 0.2802, 0.0658]])

In [2]:
tensor = torch.tensor([1,2,3])

tensor * 2



tensor([2, 4, 6])